# Generated by Django 5.2.7 on 2025-10-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('age', models.IntegerField()),
                ('branch', models.CharField(choices=[('CS', 'Computer Science'), ('AI', 'Artificial Intelligence'), ('DS', 'Data Science')], max_length=20)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
